# -*- coding: utf-8 -*-
"""lambda_Add.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xy57kM7ciiGICOimSbe-JsVmum_dXLGB
"""

# variable to store user input
val=int(input("Please Enter Any Number: "))
#Lambda Function
l = lambda val : val + 25
print(l(val))

