# -*- coding: utf-8 -*-
"""Map_Sqaure.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fd9iw1ovSj5RzPBCff7DegKKv4vY3dUQ
"""

#variable to store user input
val = list(map(int, input("Enter list of Numbers: ").split(',')))
l = list(map(lambda x: x**2, val))
print(l)

