# -*- coding: utf-8 -*-
"""Map_Triplet.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WcqMcpm_a276vzN3L00FvKtCKK1gMnSA
"""

#variable to store user input
val = list(map(int, input("Enter a list of Number: ").split(',')))
l= list(map(lambda x : x*3, val))
print(l)

